### ISSUE TITLE
Can't load entry point

### ISSUE THREAD

**Issue by coderick14** [gauthamk97/getlyrics#1]
I cloned the repo and ran `python setup.py install`. Running getlyrics gave the following stack trace

```
Traceback (most recent call last):
  File "/home/coderick14/venv/bin/getlyrics", line 11, in <module>
    load_entry_point('getlyrics==1.0', 'console_scripts', 'getlyrics')()
  File "/home/coderick14/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/coderick14/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/coderick14/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/coderick14/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named getlyrics.main
```

**Comment by gauthamk97** [comment]
Looking into the issue now. Could you try running `pip install -e .` and check if that works?

**Comment by gauthamk97** [comment]
I've updated the code and I think this should fix the issue. After pulling the changes, try running `python setup.py install` or `pip install .` and let me know if it works :)

**Comment by coderick14** [comment]
Got it working.
